@startuml
left to right direction
skinparam packageStyle rectangle

actor visiteur
actor membre

membre -|> visiteur

rectangle "POKÉMORT" {

    usecase "Demarrrer aventure" as START
    usecase "Consulter la liste des pokémons" as POKEDEX

    usecase "Démarrer un combat" as BATTLE

    usecase "Choisir une action" as LAUNCH

    usecase "Lancer une attaque" as ATTACK
    usecase "Déclencher un objet" as OBJECT
    usecase "Tenter de capturer un Pokémon" as CATCH
    usecase "Prendre la fuite" as FLEE

    visiteur -- (POKEDEX)

    membre - (START)

    (BATTLE) .>  (START) : include

    (LAUNCH) .> (BATTLE) : include
    
    (FLEE) ..> (LAUNCH) : extends
    (OBJECT) ..> (LAUNCH) : extends
    (ATTACK) ..> (LAUNCH) : extends
    (CATCH) ..> (LAUNCH) : extends


}

@enduml