@startuml
title Pokémort - Démarrer une partie

actor Visitor
participant "Front" as Front
participant "Service" as ServicePartie
participant "PartieController" as PartieCtrl

participant "Session" as Session

participant "Dao partie" as PartieDao

participant "ViewPartie" as ViewPartie

participant "DAO ViewPartie" as DaoViewPartie

participant "Membre" as Membre


Visitor -> Front : PartiePage()
Front --> Visitor : shows the starting partie page form
Visitor -> Front : sendData()
Front --> Visitor : all data are valid to start the game
Visitor -> Front : startPartie()
Front -> ServicePartie : initializePartie()
ServicePartie -> PartieCtrl : doGet()
group Start Succesfull initialization
PartieCtrl -> Session : checkConnection()
Session --> PartieCtrl : user is connected into the page
PartieCtrl -> PartieDao : somethingInProgres()
PartieDao --> PartieCtrl : no battle is in progress
end

group Create VM Partie
PartieCtrl -> DaoViewPartie : new ViewPartie() 
DaoViewPartie --> PartieCtrl : object partie
end


group Create embed Personnage
PartieCtrl -> DaoMembre : getMembre(idMembre)
DaoMembre --> PartieCtrl : return all data about member
PartieCtrl -> Partie : setMembre(Membre object)
Partie --> PartieCtrl  : ok

PartieCtrl -> ViewPersonnageDao : new DaoPersonnage()->createDefaultChaaracter()
ViewPersonnageDao -> Personnage : new Personnage()
Personnage --> PersonnageDao : 
PersonnageDao --> PartieCtrl : sends back the new personnage
PartieCtrl -> Partie : setPersonnage(Personnage personnage)
Partie --> PartieCtrl  : character of the partie is well intiialized

PartieCtrl  -> ConstituerEquipeDao : getDefault() 
ConstituerEquipeDao --> PartieCtrl : statistiques de base d'un pokémon 
end


@enduml
