@startuml

left to right direction

actor dresseur
actor ennemi

usecase "S'auhetnifier" as AUTH
usecase "Demarrrer aventure" as START
usecase "Démarrer un combat" as BATTLE
usecase "Lancer une attaque" as ATTACK
usecase "Choisir une action" as LAUNCH
usecase "Déclencher un objet" as OBJECT
usecase "Tenter de capturer un Pokémon" as CATCH
usecase "Prendre la fuite" as FLEE
usecase "Calculer les dommages" as DAMAGES
usecase "Calculer l'issu du combat" as OUTCOME

rectangle "pokemort" {
    dresseur - START
    START ...> AUTH : include
    START --- BATTLE

    ennemi - BATTLE

    LAUNCH --> BATTLE : include

    OBJECT ..> LAUNCH : extends
    CATCH ..> LAUNCH : extends
    FLEE ..> LAUNCH : extends

    ATTACK ..> LAUNCH : include

    DAMAGES ..> ATTACK : include

    OUTCOME ..> DAMAGES : include

}

@enduml