@startuml

@startuml

class Membre {
  +int mem_id
  +String mem_pseudo
  +String mem_mdp
  +String mem_nom
  +String mem_photo
}

class Statut {
  +int sta_id
  +String sta_nom
}

class Personnage {
  +int per_id
  +String per_nom
  +String per_photo
  +boolean per_jouable
  +int per_copie
}

class Type {
  +int typ_id
  +String typ_nom
  +String typ_logo
}

class Badge {
  +int bad_id
  +int bad_type
  +int bad_ordre
}

class Objet {
  +int obj_id
  +String obj_nom
  +String obj_image
}

class Pokemon {
  +int pok_id
  +int pok_numero
  +String pok_nom
  +String pok_image
  +String pok_miniature
  +int pok_base_pv
  +int pok_base_attaqie
  +int pok_base_defense
  +int pok_base_attaque_speciale
  +int pok_base_defense_speciale
  +int pok_base_vitesse
}

class Talent {
  +int tal_id
  +String tal_nom
  +int tal_fois
}

class Attaque {
  +int att_id
  +String att_nom
  +int att_puissance
  +int att_precision
}

class Effet {
  +int eff_id
  +String eff_nom
  +String eff_description
}

class Strategie {
  +int str_id
  +String str_nom
}

class Ennemi {
  +int enn_id
  +int enn_ordre
  +String enn_type
  +String enn_nom
  +String enn_phrase_debut
  +String enn_phrase_victoire
  +String enn_phrase_defaite
  +int enn_strategie
  +int enn_personnage
}

class Climat {
  +int cli_id
  +String cli_nom
}

class Partie {
  +int par_id
  +int par_membre
  +int par_personnage
  +boolean par_actif
  +int par_score
  +int par_statut
  +Date par_debut
  +Date par_fin
}

class Recompenser {
  +int rec_id
  +Date rec_date
  +int rec_partie
  +int rec_badge
}

class Delivrer {
  +int del_id
  +int del_ennemi
  +int del_badge
}

class Offrir {
  +int off_id
  +int off_ennemi
  +int off_objet
  +int off_quantite
}

class Combattre {
  +int com_id
  +int com_personnage
  +int com_ennemi
  +int com_climat
}

class SortCombattre {
  +int sor_id
  +int sor_effet
  +int sor_combattre
  +int sor_duree
}

class Decomposer {
  +int dec_id
  +int dec_effet
  +int dec_base_effet
}

class Appliquer {
  +int app_id
  +int app_effet
  +int app_objet
  +int app_ordre
}

class Exprimer {
  +int exp_id
  +int exp_talent
  +int exp_effet
}

class Declencher {
  +int dec_id
  +int dec_attaque
  +int dec_effet
}

class Engendrer {
  +int eng_id
  +int eng_statut
  +int eng_effet
}

class Craindre {
  +int cra_id
  +int cra_type_un
  +int cra_type_deux
  +int cra_effet
  +String cra_signe
}

class EtreType {
  +int etr_id
  +int etr_pokemon
  +int etre_type
}

class PeutApprendre {
  +int peu_id
  +int peu_pokemon
  +int peu_attaque
  +int peu_niveau
}

class VAEvoluer {
  +int vae_id
  +int vae_niveau
  +int vae_pokemon
  +int vae_evolution
}

class SaitExprimer {
  +int sai_id
  +int sai_pokemo


@enduml